title: brad burzon
description:  Welcome to Brad Burzon's website. Come check out Brad Burzon's blog, website design and more!.
permalink: /:categories/:title/


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

exclude: [/projects/node_modules, /projects/package-lock.json]
